/**
 * Professional Color Presets
 * Based on Minimal template for Organización RDJ Dashboard
 */

export const primaryColorPresets = {
  default: {
    name: 'Boss Lite',
    lighter: '#E3F2FD',
    light: '#90CAF9',
    main: '#1976D2',
    dark: '#1565C0',
    darker: '#0D47A1',
    contrastText: '#FFFFFF',
  },
  corporate: {
    name: 'Corporate Blue',
    lighter: '#CCF4FE',
    light: '#68CDF9',
    main: '#078DEE',
    dark: '#0351AB',
    darker: '#012972',
    contrastText: '#FFFFFF',
  },
  success: {
    name: 'Success Green',
    lighter: '#C8E6C9',
    light: '#81C784',
    main: '#4CAF50',
    dark: '#388E3C',
    darker: '#1B5E20',
    contrastText: '#FFFFFF',
  },
  finance: {
    name: 'Finance Gold',
    lighter: '#FEF4D4',
    light: '#FED680',
    main: '#FDA92D',
    dark: '#B66816',
    darker: '#793908',
    contrastText: '#1C252E',
  },
  executive: {
    name: 'Executive Navy',
    lighter: '#CDE9FD',
    light: '#6BB1F8',
    main: '#0C68E9',
    dark: '#063BA7',
    darker: '#021D6F',
    contrastText: '#FFFFFF',
  },
  creative: {
    name: 'Creative Orange',
    lighter: '#FFE3D5',
    light: '#FFC1AC',
    main: '#FF5722',
    dark: '#D84315',
    darker: '#BF360C',
    contrastText: '#FFFFFF',
  },
  modern: {
    name: 'Modern Teal',
    lighter: '#B2DFDB',
    light: '#4DB6AC',
    main: '#009688',
    dark: '#00695C',
    darker: '#004D40',
    contrastText: '#FFFFFF',
  },
  elegant: {
    name: 'Elegant Pink',
    lighter: '#F8BBD9',
    light: '#F48FB1',
    main: '#E91E63',
    dark: '#AD1457',
    darker: '#880E4F',
    contrastText: '#FFFFFF',
  },
  tech: {
    name: 'Tech Indigo',
    lighter: '#C5CAE9',
    light: '#9FA8DA',
    main: '#3F51B5',
    dark: '#303F9F',
    darker: '#1A237E',
    contrastText: '#FFFFFF',
  },
  nature: {
    name: 'Nature Green',
    lighter: '#DCEDC8',
    light: '#AED581',
    main: '#8BC34A',
    dark: '#689F38',
    darker: '#33691E',
    contrastText: '#FFFFFF',
  },
  // ðŸš€ NUEVOS COLORES EMPRESARIALES
  platinum: {
    name: 'Platinum Silver',
    lighter: '#F5F5F5',
    light: '#E0E0E0',
    main: '#9E9E9E',
    dark: '#616161',
    darker: '#424242',
    contrastText: '#FFFFFF',
  },
  royal: {
    name: 'Royal Purple',
    lighter: '#E1BEE7',
    light: '#CE93D8',
    main: '#9C27B0',
    dark: '#7B1FA2',
    darker: '#4A148C',
    contrastText: '#FFFFFF',
  },
  crimson: {
    name: 'Crimson Red',
    lighter: '#FFCDD2',
    light: '#EF9A9A',
    main: '#F44336',
    dark: '#D32F2F',
    darker: '#B71C1C',
    contrastText: '#FFFFFF',
  },
  ocean: {
    name: 'Ocean Blue',
    lighter: '#B3E5FC',
    light: '#4FC3F7',
    main: '#03A9F4',
    dark: '#0288D1',
    darker: '#01579B',
    contrastText: '#FFFFFF',
  },
  emerald: {
    name: 'Emerald Green',
    lighter: '#C8E6C9',
    light: '#A5D6A7',
    main: '#4CAF50',
    dark: '#388E3C',
    darker: '#2E7D32',
    contrastText: '#FFFFFF',
  },
  amber: {
    name: 'Amber Gold',
    lighter: '#FFF8E1',
    light: '#FFECB3',
    main: '#FFC107',
    dark: '#FFA000',
    darker: '#FF6F00',
    contrastText: '#000000',
  },
  slate: {
    name: 'Slate Gray',
    lighter: '#ECEFF1',
    light: '#B0BEC5',
    main: '#607D8B',
    dark: '#455A64',
    darker: '#263238',
    contrastText: '#FFFFFF',
  },
  burgundy: {
    name: 'Burgundy Wine',
    lighter: '#F3E5F5',
    light: '#E1BEE7',
    main: '#8E24AA',
    dark: '#7B1FA2',
    darker: '#4A148C',
    contrastText: '#FFFFFF',
  },
  forest: {
    name: 'Forest Green',
    lighter: '#E8F5E8',
    light: '#C8E6C9',
    main: '#2E7D32',
    dark: '#1B5E20',
    darker: '#0D2818',
    contrastText: '#FFFFFF',
  },
  sunset: {
    name: 'Sunset Orange',
    lighter: '#FFF3E0',
    light: '#FFCC02',
    main: '#FF9800',
    dark: '#F57C00',
    darker: '#E65100',
    contrastText: '#000000',
  },
  midnight: {
    name: 'Midnight Blue',
    lighter: '#E3F2FD',
    light: '#81D4FA',
    main: '#0277BD',
    dark: '#01579B',
    darker: '#0D47A1',
    contrastText: '#FFFFFF',
  },
  copper: {
    name: 'Copper Bronze',
    lighter: '#EFEBE9',
    light: '#D7CCC8',
    main: '#8D6E63',
    dark: '#5D4037',
    darker: '#3E2723',
    contrastText: '#FFFFFF',
  },
  lavender: {
    name: 'Lavender Purple',
    lighter: '#F3E5F5',
    light: '#E1BEE7',
    main: '#BA68C8',
    dark: '#8E24AA',
    darker: '#6A1B9A',
    contrastText: '#FFFFFF',
  },
  coral: {
    name: 'Coral Pink',
    lighter: '#FCE4EC',
    light: '#F8BBD9',
    main: '#EC407A',
    dark: '#C2185B',
    darker: '#AD1457',
    contrastText: '#FFFFFF',
  },
  steel: {
    name: 'Steel Blue',
    lighter: '#E3F2FD',
    light: '#90CAF9',
    main: '#2196F3',
    dark: '#1976D2',
    darker: '#0D47A1',
    contrastText: '#FFFFFF',
  },
  sage: {
    name: 'Sage Green',
    lighter: '#E8F5E8',
    light: '#C8E6C9',
    main: '#66BB6A',
    dark: '#4CAF50',
    darker: '#2E7D32',
    contrastText: '#FFFFFF',
  },
  magenta: {
    name: 'Magenta Pink',
    lighter: '#FCE4EC',
    light: '#F48FB1',
    main: '#E91E63',
    dark: '#C2185B',
    darker: '#880E4F',
    contrastText: '#FFFFFF',
  },
  turquoise: {
    name: 'Turquoise Blue',
    lighter: '#E0F2F1',
    light: '#80CBC4',
    main: '#26A69A',
    dark: '#00695C',
    darker: '#004D40',
    contrastText: '#FFFFFF',
  },
  lime: {
    name: 'Lime Green',
    lighter: '#F9FBE7',
    light: '#DCEDC8',
    main: '#8BC34A',
    dark: '#689F38',
    darker: '#33691E',
    contrastText: '#000000',
  },
  wine: {
    name: 'Wine Red',
    lighter: '#FFEBEE',
    light: '#FFCDD2',
    main: '#C62828',
    dark: '#B71C1C',
    darker: '#8D1818',
    contrastText: '#FFFFFF',
  }
};
